all:
  hosts:
    shared_vps:
      ansible_host: 144.91.88.242
      ansible_user: root # Tạm thời dùng root, nếu bạn setup user khác thì đổi sau
  children:
    production:
      hosts:
        shared_vps:
